backend:
  name: github
  repo: mapsync/scottsville-advisory

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "/img"
display_url: https://scottsvilleky.geosync.cloud
logo_url: https://scottsvilleky.geosync.cloud/img/logo.png

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "notification"
    label: "Notification"
    folder: "site/content/notification"
    slug: "{{year}}-{{month}}-{{day}}_{{hour}}-{{minute}}-{{second}}"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Delivery (Up to 7 days from now)", name: "delivery", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss ZZ"}
      - {label: "High Priority", name: "priority", widget: "boolean", default: false}
      - {label: "Sound", name: "sound", widget: "boolean", default: false}
      - {label: "Message", name: "message", widget: "text"}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Account", name: "account", widget: "hidden", default: "scottsvilleky"}
      - {label: "Outputs", name: "outputs", widget: "hidden", default: ["json"]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/map/_index.md"
        label: "Map Page"
        name: "map"
        fields:
          - {label: "Center", name: "center", widget: "map" }
          - {label: "Zoom", name: "zoom", widget: "number", default: 15, valuyeType: "int", min: 1, max: 20, step: 1 }
          - {label: "Alert Title", name: "label", widget: string, default: "Advisory", required: false}
          - {label: "Alert Description", name: "description", widget: text, required: false}
          - {label: "Alert Location", name: "location", widget: "map", type: "Polygon", required: false }